#!/bin/bash

create_version_h() {
    local dir=$1
    local branch=$2
    local Main_Version=$3
    local GitRevision=$4
    local GitHash=$5
    local GitCount=$6

    local VersionName="$Main_Version$(date -u +%y%m%d)$GitCount"
    local CompileDate="$(date)"
    cat <<-EOF >$dir/$branch/src/version.h
		// Do NOT edit this file, it is automatically generated prior to build.
		#ifndef VERSION
		#define VERSION "$VersionName"
		#endif

		#ifndef LMCE_version_h
		#define LMCE_version_h
		// In source files stored in archives and packages, these lines have the release version (build)
		// and the git revision information as global variables that can be inspected within a core dump
		#ifdef EXTERN_REVISION_DATE
		extern const char *g_szCompile_Date;
		extern const char *g_GitHash;
		extern int g_GitCommitCount;
		#else
		const char *g_szCompile_Date="$CompileDate";
		const char *g_GitHash="$GitHash";
		int g_GitCommitCount=$GitCount;
		#endif
		#endif
		EOF
}